app/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static 
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [

    #strona główna(muszą być oba bo inaczej error)
    path('', views.start, name='home'),
    path('', views.start, name='index'),

    #rejestracja i przypominanie hasła
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
#działa
    url(r'^password_change/$', views.change_password, name='change_password'),
    

#działa
    url(r'^accounts/password_reset/$', auth_views.PasswordResetView.as_view(template_name = "registration/password_reset.html"),name ='reset_password'),

#działa
    url(r'^accounts/password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name = "registration/password_reset_sent.html"), name ='password_reset_done'),

#działa pod warunkiem, że nie folder "registrations" tylko "accounts"
    url(r'accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name = "accounts/password_reset_confirm.html"), name ='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name = "accounts/password_reset_done.html"), name ='password_reset_complete'),

  

    #Podgląd profilu
    path('profile/<int:user>/', views.profile, name='profile'),
    

    #Szukaj korepetytorów
    path('search/', views.search, name='search'),

    #Lista korepetytorów
    path('list/', views.list, name='list'),

     #Lista uczniów
    path('councils_list/', views.councils_list, name='councils_list'),

    #Chybił trafił
    path('random/', views.random, name='random'),

    #Chybił trafił
    path('random.html', TemplateView.as_view(template_name="profile_view.html")),

    #Edycja przedmiotów oraz miejscowości
    path('edit_personal/', views.edit_personal, name='edit_personal'),

    #Edycja danych osobowych
    path('edit/', views.edit, name='edit'),

    #Report profilu
    path('report/<int:user>/', views.report, name='report'),

    #Rating profilu
    path('rate/<int:user>/', views.rate, name='rate'),
    
    path('comment/<int:user>/', views.comment, name='comment'),

    path('meeting/<int:user>/', views.meet, name='meet'),

    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),

    path('ranking/', views.ranking, name='ranking'),

    path('comments/<int:user>/', views.comment_view, name='comments'),

    path('meetings/<int:user>/', views.meeting_view, name='meetings'),

    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),

    path('api/messages/', views.message_list, name='message-list'),

    path('contact/', views.contact, name='contact'),

#    path('friend_invite_sent/', views.invite_friend, name='friend_invite_sent')


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

korepder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views



urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

app/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from PIL import Image
import random
from multiselectfield import MultiSelectField

#Model post
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    user_commented = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_commented')
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{self.author.username} ->  {self.user_commented.username} ({self.text})'


class Meeting(models.Model):
    tutor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tutor')
    council = models.ForeignKey(User, on_delete=models.CASCADE, related_name='council')
    meeting_title = models.CharField(max_length=30)
    meeting_description = models.TextField()
    planned_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.save()

    
    def __str__(self):
        return f'{self.tutor.username} ->  {self.council.username} ({self.meeting_title},{self.meeting_description})'

#Model profilu
class Profile(models.Model):


    def random_string():
        return "gest" + str(random.randint(1, 5)) + ".png"


    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='none.jpg', upload_to='profile_pics')

    wzor = models.ImageField(default=random_string, upload_to='profile_auth')
    zdjecie = models.ImageField(default='none.jpg', upload_to='profile_auth')

    PRZEDMIOTY_CHOICES = [
    ('brak', 'Brak'),
    ('historia', 'Historia'),
    ('angielski', 'Angielski'),
    ('informatyka', 'Informatyka'),
    ('matematyka', 'Matematyka'),
    ('polski', 'Polski'),
    ]

    MIEJSCOWOSC_CHOICES = [
    ('brak', 'Brak'),
    ('Warszawa', 'Warszawa'),
    ('Gdynia', 'Gdynia'),
    ('Kraków', 'Kraków'),
    ('Poznań', 'Poznań'),
    ('Wrocław', 'Wrocław'),
    ('Ciechanów', 'Ciechanów'),
    ]

    RANGA_CHOICES = [
    ('brak', 'Brak (0-1199)'),
    ('wood', 'Wood (1200-1399)'),
    ('leaf', 'Leaf (1400-1599)'),
    ('gold', 'Gold (1600-1799)'),
    ('diamond', 'Diamond (1800-)'),
    ]

    zweryfikowany = models.BooleanField(default=False)
    przedmiot = MultiSelectField(choices=PRZEDMIOTY_CHOICES, default='brak')
    miejscowosc = models.CharField(max_length=30, choices=MIEJSCOWOSC_CHOICES, default='brak')
    cena = models.PositiveIntegerField(default='0')
    punkty = models.CharField(max_length=7, default=1000)
    ranga = models.CharField(max_length=30, choices=RANGA_CHOICES, default="brak")
    opis = models.TextField(max_length="500", default='Uzupełnij opis aby Twój profil cieszył się większą popularnością.')
    korepetytor = models.BooleanField(default=False)
    users = User.objects.all()
    args = {'users':users,}

    def __str__(self):
        return f'{self.user.username} - Profil'


   
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)



#Model zgłoszeń użytkowników
class Report(models.Model):
    user_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_author')
    user_reported = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_reported')
    message = models.TextField()

    def __str__(self):
        return f'{self.user_author.username} ->  {self.user_reported.username} ({self.message})'





#Model ocen użytkowników
class Rate(models.Model):
    user_rate_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_rate_author')
    user_rated = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_rated')
    ocena = models.CharField(max_length=7)

    def __str__(self):
        return f'{self.user_rate_author.username} ->  {self.user_rated.username} ({self.ocena})'


def random_string():
    return "gest" + str(random.randint(1, 5)) + ".png"



#Model weryfikacji
class Auth(models.Model):
    user_auth_author = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_auth_author')
    wzor = models.ImageField(default=random_string, upload_to='profile_auth')
    zdjecie = models.ImageField(default='none.jpg', upload_to='profile_auth')

    def __str__(self):
        return f'{self.user_auth_author.username}'


   

    

    


#Model wiadomości
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

app/templates/app/chat_tlo.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <link type="text/css" rel="stylesheet" href="{% static 'app/css/materialize.min.css' %}"  media="screen,projection"/>
        <link rel="stylesheet" href="{% static 'app/css/chat_tlo.css' %}">
        <script type="text/javascript" src="{% static 'app/js/chat.js' %}"></script>
    </head>

    <body style="background-color: #F0F0F0;">
    {% block body %}
        
    {% endblock %}
    </body>

  </html>


  

app/templates/app/edit_personal.html
{% extends 'app/main_tlo.html' %} 


{% block content %}

<form method="POST" enctype="multipart/form-data">

    <legend class="border-bottom mb-4">Ustawienia wyszukiwania</legend>
    <div class="field edit">
    <form method="post" enctype="multipart/form-data">
        <ul class="list-group list-group-flush border-bottom mb-4" style="height: 520px; width: 100%; overflow-x:hidden; float: left;">
            <li class="list-group-item">
                <div class="textbox" style="width: 20%; font-size: large;">
                    <label style="float: left;">Przedmiot:</label>
                    {{ profile_settings_form.przedmiot }}
                </div>
                <div class="textbox" style="width: 20%; font-size: large;">
                    <label style="float: left;">Miejscowość:</label>
                    {{ profile_settings_form.miejscowosc }}
                </div>
                <div class="textbox" style="width: 20%; font-size: large;">
                    <label style="float: left;">Cena:</label>
                    {{ profile_settings_form.cena }}
                </div>
            {% csrf_token %}
            
            </li>
        
        </ul>
        <div class="textbox" style="width: 50%; padding-top: 420px; padding-bottom: 10px;">
            <p><input type="submit" class="btn btn-secondary" value="Zapisz zmiany"></p>
        </div>
        </form>
        
    </div>
</form>
{% endblock %}

app/templates/app/index.html
{% extends 'app/main_tlo.html' %} 

{% block content %}

        {% if user.profile.zweryfikowany == True %}
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <center>
                        <img src="https://i.ibb.co/3NSN9sF/zdjecie1.png" class="d-block h-100" alt="...">                    </center>
                    <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                    </div>
                </div>
                <div class="carousel-item">
                    <center>
                        <img src="https://i.ibb.co/sy5vs7W/zdjecie2.png" class="d-block h-100" alt="...">                    </center>
                    <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                    </div>
                </div>
                <div class="carousel-item">
                    <center>
                        <img src="https://i.ibb.co/SND8X4g/zdjecie3.png" class="d-block h-100" alt="...">                    </center>
                    <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                    </div>
                </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>
            {% else %}
            <div class="row">
                <div style="margin-left: 40px;">
                    <p>Twoje zgłoszenie czeka na przeanalizowanie przez naszych administratorów. Prosimy o cierpliwość.</p>
                </div>

                <div class="col-11" style="text-align: center">
                    <b>Wzór</b>
                    <br>
                    <img src="{{request.user.profile.wzor.url}}" width="200" height="200" alt="avatar">
                </div>

                <div class="col-11" style="text-align: center; margin-top: 30px;">
                    <b>Twoje zdjęcie</b>
                    <br>
                    <img src="{{request.user.profile.zdjecie.url}}" width="200" height="200" alt="avatar2">
                </div>

            </div>
            {% endif %}


            

        

{% endblock %}

app/templates/app/list.html
{% extends 'app/main_tlo.html' %}


{% block content %}


<legend class="border-bottom mb-4">Lista korepetytorów</legend>

<form action = "" method = "get">
    {% csrf_token %}
     <!-- <label for="subject">Podaj szukany przedmiot: </label> -->
     <select class="listLabel" name="subject">
        <option value="angielski">Angielski</option>
        <option value="historia">Historia</option>
        <option value="polski">Polski</option>
        <option value="matematyka">Matematyka</option>
        <option value="informatyka">Informatyka</option>
    </select>

    <!-- <label for="price">Podaj cene: </label> --> 
    <input class="inputData" id="priceLow" type="number" name="priceLow" value="" placeholder="Cena Minimalna">

    <input class="inputData" id="priceHigh" type="number" name="priceHigh" value="" placeholder="Cena Maksymalna">

    <select class="inputData" name="city">
        <option value="Warszawa">Warszawa</option>
        <option value="Gdynia">Gdynia</option>
        <option value="Kraków">Kraków</option>
        <option value="Poznań">Poznań</option>
        <option value="Wrocław">Wrocław</option>
        <option value="Ciechanów">Ciechanów</option>
    </select>
<input type="submit" class="btn btn-secondary " value="Filtruj" style="margin-left:50px; background-color: rgb(255, 255, 255); color: black; border-color: rgb(150, 235, 166);">
</form>


<ul class="list-group list-group-flush" style="overflow-x:hidden; border-radius: 5px 5px 5px 5px; max-height: 5000px; height: 530px; " >
    <li class="list-group-item" style="background:transparent; border-radius: 5px 5px 5px 5px;">
    <div class="row">
        {% for user in users %}
        {% if user.profile.korepetytor %}   <!-- sprawdza czy profil do wyswietlenia jest nauczycielem -->
        {% if user.profile.cena <= priceHigh and user.profile.cena >= priceLow and user.profile.miejscowosc == city and lesson|lower in user.profile.przedmiot %}   <!-- sprawdza czy profil spelnia wymagania filtrow -->
        <div class="col-4">
            <div class="user_card" style="height: 250px; width: 180px; background-image: linear-gradient(rgb(80, 219, 177),rgb(111, 240, 122)); float: left; margin: 30px; border-radius: 5px 5px 5px 5px; box-shadow: 0px 4px 5px 1px #1b1b1b;" >
                <img class="rounder-circle account-img" src="{{user.profile.image.url}}" height="130px" width="130px" style="margin-top: 10px; border-radius: 50px 50px 50px 50px;"><br>
                <div id="name">{{user.first_name}} {{user.last_name}}</div><br>
                <a href="{% url 'profile' user.id %}">
                <button type="button" class="btn btn-light" style="position:absolute; bottom:40px; right:58px;">Zobacz profil</button>
                </a>
            </div> 
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}
    </div>
</li>
</ul>


<script>

    
</script>
{% endblock %}

app/templates/app/meetings.html
{% extends 'app/main_tlo.html' %}
{% block content %}

    <legend class="border-bottom mb-4">Spotkania</legend>

    <ul style="max-height: 600px; overflow:hidden; overflow-y:scroll;">
    {% for meeting in meetings %}
    {% if meeting.tutor.username %}
    <div class="card-panel left green lighten-3" style="width: 75%; position: relative; background-color: rgb(88, 88, 88); border-radius: 5px 5px 5px 5px; padding: 5px">
        <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ meeting.tutor.first_name }} {{ meeting.tutor.last_name}}</div><br>
        <h6>{{ meeting.meeting_title }}</h6>
        {{ meeting.meeting_description }}<br>
        <span style="color: rgb(180, 180, 180);">{{meeting.planned_date}}</span>

    </div>
    <br>
    {% endif %}
    {% endfor %}

</ul>

{% if request.user.id != user.id %}
    {% if user.profile.korepetytor %}
        <a class="nav-item">
            <a class="nav-link" href="{% url 'meet' user.id%}" style="margin-left: 2px; width: 160px; border-radius: 5px 5px 5px 5px; border-color: rgb(23, 209, 47); border-style: solid; position: absolute; bottom: 20px;">
                <span class="media-body">Dodaj spotkanie</span>
            </a>
        </a>
    {% endif %}
{% endif %}

{% endblock %}

app/templates/app/panel_podglad.html
{% extends 'app/main_tlo.html' %} 

{% block content %}

<div>

    <div class="media">
        <img class="rounder-circle account-img" src="{{user.profile.image.url}}" height="130px" width="130px">
        <div class="media-body" style="margin-left: 10px;">
            <br>
            <br>
            <br>
            
        </div>
    </div>
    <h2 class="account-heading">{{user.first_name}} {{user.last_name}}</h2>
    {% if user.profile.korepetytor == True %}
    <h5>Korepetytor</h3>
{% else %}
    <h5>Uczeń</h3>   
{% endif %}

    <br>
    <legend class="border-bottom mb-4">Opis</legend>
    <ul class="list-group list-group-flush" style="height: 300px; overflow-x:hidden;">
        <li class="list-group-item">

                <div class="uzytkownik_opis" id="opis_panel" style="float:left;">
                {{user.profile.opis}}
                </div>

        </li>
    </ul>
    <br>
    <legend class="border-bottom mb-4">Przedmioty</legend>
    {% for user.przedmiot in user.przedmiots%}
    <div class="jezyk_box" style="padding: 5px; display: inline-block; border-radius: 5px; height: 2em; border: 2px solid rgb(35, 151, 40); outline: none; text-align: center;"><p>{{user.profile.przedmiot}}</p></div>
    <div class="jezyk_box" style="padding: 5px; display: inline-block; border-radius: 5px; height: 2em; border: 2px solid rgb(35, 151, 40); outline: none; text-align: center;"><p>{{user.profile.przedmiot}}</p></div>
    <div class="jezyk_box" style="padding: 5px; display: inline-block; border-radius: 5px; height: 2em; border: 2px solid rgb(35, 151, 40); outline: none; text-align: center;"><p>{{user.profile.przedmiot}}</p></div>
    {% endfor %}
</div>
{% endblock %}

app/templates/app/personal_information_edit.html
{% extends 'app/main_tlo.html' %} 


{% block content %}

<div>

    <div class="media">
        <img class="rounder-circle account-img" src="{{user.profile.image.url}}" height="130px" width="130px">
    </div>


    <form method="POST" enctype="multipart/form-data">

        <legend class="border-bottom mb-4">Informacje o profilu</legend>
        
        <form method="post" enctype="multipart/form-data">
            <ul class="list-group list-group-flush" style="height: 400px; overflow-x:hidden; float:left">
                <li class="list-group-item">
                    <div class="textbox">
                        Przedmiot:
                        {{ profile_settings_form.przedmiot }}
                    </div>
                    <div class="textbox">
                        Miejscowość:
                        {{ profile_settings_form.miejscowosc }}
                    </div>
                {% csrf_token %}
            
                <p><input type="submit" value="Zapisz zmiany"></p>
            </li>
            </ul>
            </form>

    </form>
</div>
{% endblock %}

app/templates/app/profile_view.html
<div style="background-color: rgb(34, 34, 34); border-radius: 10px 10px 10px 10px;">

    <div class="media" style="width: 755px;">
        <img class="rounder-circle" src="{{user.profile.image.url}}" height="130px" width="130px" style="border-radius: 5px; border-width: 2px; border-style: solid; border-color: rgb(125, 196, 160);">
        <div class="media-body account-img" style="margin-left: 10px;  border-right-width: 5px; border-color: seagreen;">
            <br>
            {% if user.profile.korepetytor == True %}
            <h5 style="color:rgb(47, 184, 54)">Korepetytor</h3>  
        {% else %}
            <h5 style="color:rgb(47, 184, 54)">Uczeń</h3>   
        {% endif %}
        <h4 style="color:rgb(77, 167, 82)">{{user.profile.miejscowosc}}</h4> 
            <h2 class="account-heading" style="color: rgb(119, 189, 122);">{{user.first_name}} {{user.last_name}}</h2>
        </div>
        {% if request.user.id != user.id %}
    
    
        

        {% endif %}
    </div>
    <br>

    
    

    <br>
    <legend class="border-bottom mb-4">Opis</legend>
    <ul class="list-group list-group-flush" style=" overflow-x:hidden; max-height: 300px;">
        <li class="list-group-item" style=" background-color: gray; border-radius: 10px; height: 280px; max-width: 500px; ">

                <div class="uzytkownik_opis" id="opis_panel" style="float:left; max-width: 460px;">
                {{user.profile.opis}}
                </div>

        </li>
    </ul>
    <br>
    <legend class="border-bottom mb-4">Przedmioty</legend>
    {% for przedmiot in user.profile.przedmiot %}
        <div class="jezyk_box" style="padding: 5px; display: inline-block; border-radius: 5px; height: 2em; background-color: rgb(58, 58, 58); border: 2px solid rgb(35, 151, 40); outline: none; text-align: center; color: #AAA;">
            <p>{{przedmiot}}</p></div>
    {% empty %}
        <p>Brak przedmiotów</p>
    {% endfor %}
</div>

app/templates/app/random.html
{% extends 'app/main_tlo.html' %} 


{% block content %}

{% if user.profile.korepetytor %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="background-color: transparent; padding: 5px; max-height: 660px; ">
    <div>
        <div class="media" style="width: 700px;">
            {% include "app/profile_view.html" %}
        </div>
    <br>
</div>
<div style="background-color: transparent;" ></div>
<button type="button" class="btn" onClick="window.location.reload();" style="margin-left: 320px; position: absolute; bottom: -38px; background-color: rgb(230, 42, 42);">Dalej</button>
<a href="{#}">
<button type="button" class="btn" style="position: absolute; bottom: -38px; left: 390px; background-color: rgb(8, 126, 53);">Dodaj</button>
</a>
</div>
{% else %}
window.location.reload(true);
<p>Natrafiłeś na ucznia, szukaj dalej</p>
<button type="button" class="btn" onClick="window.location.reload();" style="margin-left: 320px; position: absolute; bottom: 10px; left: 120px; background-color: rgb(230, 42, 42);">Dalej</button>
{% endif %}





{% endblock %}

app/templates/app/rate_error.html
{% extends 'app/main_tlo.html' %} 

{% block content %}




    <div class="col-11" style="margin-left: 30px;">
       <div class="card shadow-lg">
          <div class="text-center" style="width: 80%;margin: 0 auto; height: 100px;">
            <h1 style="font-size: 15px;margin-top: 40px;">Juz oceniłeś tego użytkownika</h1> 
          </div>
       </div>
    </div>
{% endblock %}

app/templates/app/report.html
{% extends 'app/main_tlo.html' %} 


{% block content %}

<div>

    
    <form method="POST" enctype="multipart/form-data">

        <legend class="border-bottom mb-4">Report</legend>
        
        <form method="post" enctype="multipart/form-data">
            <ul class="list-group list-group-flush" style="height: 400px; overflow-x:hidden; float:left">
                <div class="textbox" style="text-align: center;">
                    <p>Napisany report zostanie jak najszybciej przeanalizowany przez administrację oraz zostaną wyciągnięte odpowiednie wnioski.</p>
                    <div class="textbox">
                        <input type="text" name="message" required="" id="id_message" style="width: 600px;">
                    </div>
                    <button type="submit" name="report" class="btn btn-success" style="margin-left: 13px; width: 150px; margin-top: 50px;">Wyślij report</button>
                </div>
                    
                {% csrf_token %}
                    
            </ul>
            </form>

    </form>
</div>

{% endblock %}

app/templates/app/start_tlo.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Title</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Druga strona"/>
	    <meta name="keywords" content="korepder, korki, jakubpikus, wojteklatek"/>
		
		
		
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">
        
        <link rel="stylesheet" href="{% static 'app/css/start_tlo.css' %}">
    </head>
    <body >

  

    


        <div class="row justify-content-center d-md-table mx-auto" style="padding-top: 50px; padding-bottom: 50px;">
            <a href="{% url 'index' %}"><img src="{% static '/app/css/images/korepder_logo.png' %}" style="height: 160px; padding: 30px"></a>
        </div>


            
        <div class="row justify-content-center d-md-table mx-auto">

                    
                    {% block content %}
                    {% endblock content %}
                    
                
        </div>
        


    
<script src="https://kit.fontawesome.com/75f758938c.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script>
    
    
    


</script>
</body>
</html>